### ISSUE TITLE
    java.lang.RuntimeException: java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes4.dex)

### ISSUE THREAD

**Issue by dayona** [yaphet17/chapa-java#11]
RuntimeException on the line 
`InitializeResponseData responseData = chapa.initialize(postData);`

java.lang.RuntimeException: java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes4.dex)
        at com.dspread.demoui.activities.TransactionActivity$1.onClick(TransactionActivity.java:111)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes4.dex)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.getSocketFactory(SSLConnectionSocketFactory.java:172)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.getDefaultRegistry(PoolingHttpClientConnectionManager.java:109)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:116)
        at com.mashape.unirest.http.options.Options.refresh(Options.java:72)
        at com.mashape.unirest.http.options.Options.<clinit>(Options.java:46)
        at com.mashape.unirest.http.options.Options.getOption(Options.java:42)
        at com.mashape.unirest.http.HttpClientHelper.prepareRequest(HttpClientHelper.java:151)
        at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:131)
        at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
        at com.yaphet.chapa.client.ChapaClientImpl.post(ChapaClientImpl.java:34)
        at com.yaphet.chapa.Chapa.initialize(Chapa.java:95)
        at com.dspread.demoui.activities.TransactionActivity$1.onClick(TransactionActivity.java:97)
        at android.view.View.performClick(View.java:7448) 
        at android.view.View.performClickInternal(View.java:7425) 
        at android.view.View.access$3600(View.java:810) 
        at android.view.View$PerformClick.run(View.java:28305) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7664) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by yaphet17** [comment]
I don't see anything related to this library. Can you add more description?

**Comment by dayona** [comment]
> I don't see anything related to this library. Can you add more description?

I have used the example from the readme and i have this error.  Iam attaching the code here.

`public class MainActivity extends AppCompatActivity {
 
    private EditText firstName;
    private EditText lastName;
    private EditText _email;
    private EditText _amount;
    private EditText _mobile;
    private EditText _tx_ref;
    private EditText _currency;
    private Button proceed;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
 
        firstName = findViewById(R.id.first_name);
        lastName = findViewById(R.id.last_name);
        _email = findViewById(R.id.email);
        _amount = findViewById(R.id.amount);
        _mobile = findViewById(R.id.mobile);
        _currency = findViewById(R.id.currency);
 
        proceed = findViewById(R.id.proceed);
        proceed.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
 
                Chapa chapa = new Chapa("Test_Secret_Key");
 
                // Retrieve user input from EditText views
                String firstname = firstName.getText().toString();
                String lastname = lastName.getText().toString();
                String email = _email.getText().toString();
                String amount = _amount.getText().toString();
                String mobile = _mobile.getText().toString();
                String tx_ref = Util.generateToken();
                String currency = _currency.getText().toString();
 
                Customization customization = new Customization()
                        .setTitle("Technologies")
                        .setDescription("It is time to pay");
                PostData postData = new PostData()
                        .setAmount(new BigDecimal(amount))
                        .setCurrency("ETB")
                        .setFirstName(firstname)
                        .setLastName(lastname)
                        .setEmail(email)
                        .setTxRef(tx_ref)
                        .setCallbackUrl("https://chapa.co")
                        .setReturnUrl("https://chapa.co")
                        .setCustomization(customization);
 
                try {
                    InitializeResponseData responseData = chapa.initialize(postData);
                    // Get the response message
                    System.out.println(responseData.getMessage());
                    // Get the checkout URL from the response JSON
                    System.out.println(responseData.getData().getCheckOutUrl());
                    // Get the raw response JSON
                    System.out.println(responseData.getRawJson());
                    VerifyResponseData verifyResponseData = chapa.verify(tx_ref);
                    if (verifyResponseData.getStatus().equals("success")) {
                        Toast.makeText(getApplicationContext(),"Payment Verified!",Toast.LENGTH_SHORT).show();
                    } else {
                        Toast.makeText(getApplicationContext(),"Payment Not Verified!",Toast.LENGTH_SHORT).show();
                    }
                } catch (Throwable e) {
                    throw new RuntimeException(e);
                }
 
            }
        });
    }`

**Comment by yaphet17** [comment]
Sorry for the late reply. What version of JDK are you using? I suspect JDK that is less than 8.
